name: docs
on:
  push:
    branches:
      - main
      - develop
    paths:
      - README.md
      - .github/workflows/docs.yml

  workflow_dispatch: # Allow manual triggering

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    name: pandoc to vimdoc
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: panvimdoc
        uses: kdheepak/panvimdoc@main
        with:
          vimdoc: checkmate
          version: "Neovim >= 0.10.0"
          demojify: true
          treesitter: true
      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "auto-generate vimdoc"
          commit_user_name: "github-actions[bot]"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
          commit_author: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"
          branch: ${{ github.head_ref }}
