---
name: lint-test
on:
  push:
    branches:
      - main # Only run on push to main
  pull_request:
    branches:
      - main # Run on PRs targeting main
  workflow_dispatch: # Allow manual triggering

jobs:
  stylua:
    name: stylua
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: JohnnyMorganz/stylua-action@v3
        with:
          version: latest
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --color always --check lua

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nvim-versions: ["stable", "nightly"]
    name: test
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: setup neovim
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: ${{ matrix.nvim-versions }}
      # Install Lua and LuaRocks - for busted and other dependencies
      - name: Setup Lua
        uses: leafo/gh-actions-lua@v11
        with:
          luaVersion: "5.1" # match Neovim's Lua version
      - name: Setup LuaRocks
        uses: leafo/gh-actions-luarocks@v5
      - name: run tests
        run: make test
