name: Release Please

on:
  push:
    branches:
      - main
      - "release/**"

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    env:
      HUSKY: 0 # don't run husky hooks in CI
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Release Please
        uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.PAT }}
          config-file: release-please-config.json
          # Tell it to open/update the PR against whichever branch triggered this run:
          target-branch: ${{ github.ref_name }}
